### ISSUE TITLE
The building of VC.gltf is collapsed and displayed

### ISSUE THREAD

**Issue by cx20** [PrincessGod/CraZyPG#1]
I tried to display VC.gltf using CZPG.js.
[![image](https://user-images.githubusercontent.com/1833979/39391520-8790d102-4adf-11e8-82e3-8b185dfcef91.png)](https://github.com/cx20/gltf-test#more-complex-models)

However, it seems that some buildings are collapsed and displayed.

[CZPG.js + VC.gltf result:](https://cx20.github.io/gltf-test/examples/czpg/index.html?model=VC&scale=0.2)
![image](https://user-images.githubusercontent.com/1833979/39391442-6917f9cc-4ade-11e8-9021-1ed4623f53b5.png)

BTW, Which name should I use CZPG or CraZyPG?

**Comment by PrincessGod** [comment]
@cx20  Thank you!

Actually my quaternion has some problem, and I will fix that.
After fixed, I will help you to update.
CZPG.js is fine.

BW :)

**Comment by PrincessGod** [comment]
@cx20 Hi.

I have fixed these problem, also make gui.autoRotate working.
So maybe you should update czpg.js and sample page.

Thanks!

**Comment by cx20** [comment]
I confirmed that the inclination of the building has been improved.
![image](https://user-images.githubusercontent.com/1833979/39520561-1e1bda0e-4e46-11e8-9bef-a3437b9e11e0.png)

I also understood about the thing that does not stop rotation with it and dat.gui. The gltf-test sample has been fixed.

**Comment by PrincessGod** [comment]
@cx20 
About the model `Gearbox Assy`, it is far away from origin, you can see it in [Babylon.js](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?model=GearboxAssy&scale=1).
To see it you can make skybox more bigger, for example [1000](https://github.com/PrincessGod/CraZyPG/blob/083de8f3ba8f4759e8380592fa833f1680abb7ff/sample/gltfloader.html#L143) other than [200](https://github.com/cx20/gltf-test/blob/d1cc8cf17418de6ece27e6df23a4d0ebb2097525/examples/czpg/index.js#L109).

Maybe you can update gui with [animation controler](https://github.com/PrincessGod/CraZyPG/blob/master/sample/gltfloader.html#L123-L132) too?

**Comment by cx20** [comment]
In the sample of other libraries of gltf-test, we have included a code that forcibly modifies the position of `Gearbox Assy`.
Below is a sample code of Three.js.
```javascript
if (modelInfo.name == "GearboxAssy" ) {
    scale = 0.2;
    object.scale.set(scale, scale, scale);
    object.position.set(-159.20*scale, -17.02*scale, -3.21*scale);
} else {
    object.scale.set(scale, scale, scale);
}
```
I will add a similar alignment code for CZPG.js. However, I do not understand how to use the library, so I will look it up from now.

**Comment by cx20** [comment]
I added the following code as a sample of Three.js. I think that `Gearbox Assy` is now displayed.
```javascript
if (modelInfo.name == "GearboxAssy" ) {
    scale = 0.2;
    sceneNode.setScale(scale, scale, scale);
    sceneNode.transform.position = [-159.20*scale, -17.02*scale, -3.21*scale];
} else {
    sceneNode.setScale(scale, scale, scale);
}
```
Please point out if there is an error in how to use the library.

**Comment by cx20** [comment]
[CZPG.js + GearboxAssy.gltf result:](https://cx20.github.io/gltf-test/examples/czpg/index.html?model=GearboxAssy&scale=1)
![image](https://user-images.githubusercontent.com/1833979/39521517-c6a6271c-4e49-11e8-8bba-ffdf57ad7dbb.png)

**Comment by PrincessGod** [comment]
@cx20  Sorry about reply too late.

Actually you can just use
```js
if (modelInfo.name == "GearboxAssy" ) {
    scale = 0.2;
    sceneNode.scale = [scale, scale, scale];
    sceneNode.position = [-159.20*scale, -17.02*scale, -3.21*scale];
} else {
    sceneNode.scale = [scale, scale, scale];
}
```

**Comment by cx20** [comment]
@PrincessGod Thank you for telling me how to use. I fixed the sample of gltf-test.

**Comment by PrincessGod** [comment]
@cx20  Shame of myself. This is what I should do.
