### ISSUE TITLE
Matrix4.perspective fov usage is incorrect

### ISSUE THREAD

**Issue by cx20** [PrincessGod/CraZyPG#10]
This Issue is the posting of the following report.
https://github.com/cx20/gltf-test/issues/34#issuecomment-387103421

A window zoom or resize will trigger this line here:

https://github.com/cx20/gltf-test/blob/bcef1b495f99c5d340341f1310ea74736cd47942/examples/czpg/index.js#L139

In `PerspectiveCamera.prototype.updateProjMatrix`, this line is executed:

```
        Matrix4.perspective( this.projMat, this.fov, this.aspect, this.near, this.far );
```

But, `this.fov` is in degrees, not radians.  The `Matrix4.perspective` function tries to use the value as radians, and gets confused.  The projection matrix is then flipped over.

**Comment by PrincessGod** [comment]
@cx20  thanks!  you can check if it works right now!

**Comment by cx20** [comment]
@PrincessGod  I confirmed that the issue was solved.
http://jsdo.it/cx20/eOoY
