### ISSUE TITLE
How can I use the camera embedded in the glTF model?

### ISSUE THREAD

**Issue by cx20** [PrincessGod/CraZyPG#11]
Cameras are built into the glTF model of `Polly` and `Virtual City`.
The following is an example of use in Three.js of a camera incorporated in Polly's glTF model.
http://jsdo.it/cx20/Cnr2
I think that it is wonderful if this feature can be used in CZPG.js. Is this possible?

**Comment by PrincessGod** [comment]
@cx20   I will support it in a week, maybe tomorrow :)

**Comment by PrincessGod** [comment]
@cx20  Hi.

I had put camera into `Scene`, and parse cameras in glTF, all you want is `Scene.setCamera(camera)`.

 And the camera in glTF can be pull out by [this way](https://github.com/PrincessGod/CraZyPG/blob/master/sample/gltfloader.html#L114-L136).
Also do not forget [this line](https://github.com/PrincessGod/CraZyPG/blob/master/sample/gltfloader.html#L177), and all `Shader` do not have to init with camera.

**Comment by cx20** [comment]
I confirmed that can use the built-in camera of glTF in the latest version of CZPG.js.

![image](https://user-images.githubusercontent.com/1833979/39970635-d160199a-5729-11e8-9146-f34a7e171914.png)

![image](https://user-images.githubusercontent.com/1833979/39970641-ecd904de-5729-11e8-950a-02513b9ca991.png)

http://jsdo.it/cx20/6dru
![image](https://user-images.githubusercontent.com/1833979/39970786-aed1dca8-572c-11e8-8251-14b9e6f511cf.png)
