### ISSUE TITLE
Polly's eyeball does not seem to be displayed

### ISSUE THREAD

**Issue by cx20** [PrincessGod/CraZyPG#12]
I compared the execution results of CZPG.js with other WebGL libraries.

[CZPG.js + Polly result:](http://jsdo.it/cx20/6dru)
![image](https://user-images.githubusercontent.com/1833979/40130701-c8f0c818-5972-11e8-9a9c-4322ee71024c.png)

[Three.js + Polly result:](http://jsdo.it/cx20/Cnr2)
![image](https://user-images.githubusercontent.com/1833979/40130757-ef613668-5972-11e8-85e4-078a0a9cf107.png)

Polly eyeball think green is correct.

Related:
https://www.youtube.com/watch?v=l7TB1O51X_M

**Comment by PrincessGod** [comment]
Thanks!  Think it fixed, [link](http://princessgod.com/CraZyPG/gltfloader.html)

**Comment by cx20** [comment]
I confirmed that the eyeball appears in Polly.
http://jsdo.it/cx20/6dru
![image](https://user-images.githubusercontent.com/1833979/40206017-49fc4df0-5a69-11e8-8ef4-9f2070b02e3f.png)
