### ISSUE TITLE
Failure to load the texture of the cross origin 

### ISSUE THREAD

**Issue by cx20** [PrincessGod/CraZyPG#3]
I tried to access [github's resource](https://github.com/cx20/gltf-test/) from [RawGit](https://rawgit.com/) service from [jsdo.it](http://jsdo.it/).

http://jsdo.it/cx20/ESde

However, because of the cross origin restriction, it could not be displayed.

```javascript
czpg.js:6712 
Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': The image element contains cross-origin data, and may not be loaded.
    at getCubeFacesOrder.forEach (https://cdn.rawgit.com/cx20/gltf-test/91ebb79a/libs/czpg/20180503/czpg.js:6712:28)
    at Array.forEach (<anonymous>)
    at https://cdn.rawgit.com/cx20/gltf-test/91ebb79a/libs/czpg/20180503/czpg.js:6710:45
    at Image.onLoad (https://cdn.rawgit.com/cx20/gltf-test/91ebb79a/libs/czpg/20180503/czpg.js:6200:9)
```

Perhaps when accessing via RawGit, you can access it by specifying `anonymous` as the crossOrigin attribute.
```javascript
img.crossOrigin = "anonymous";
```
Please provide a way to access the resources of the cross origin constraint with CZPG.js.

**Comment by PrincessGod** [comment]
@cx20 
Actually about this part I use TWGL.js like API, so just add `crossOrigin: 'anonymous'` to specify CORS.
```js
        env: {
            target: context.TEXTURE_CUBE_MAP,
            crossOrigin: 'anonymous',
            src: [
                'https://cdn.rawgit.com/cx20/gltf-test/c479d543/textures/cube/skybox/px.jpg',
                'https://cdn.rawgit.com/cx20/gltf-test/c479d543/textures/cube/skybox/nx.jpg',
                'https://cdn.rawgit.com/cx20/gltf-test/c479d543/textures/cube/skybox/py.jpg',
                'https://cdn.rawgit.com/cx20/gltf-test/c479d543/textures/cube/skybox/ny.jpg',
                'https://cdn.rawgit.com/cx20/gltf-test/c479d543/textures/cube/skybox/pz.jpg',
                'https://cdn.rawgit.com/cx20/gltf-test/c479d543/textures/cube/skybox/nz.jpg',
            ]
        }
```

Also optimized your sample, [http://jsdo.it/PrincessGod/g2PE](http://jsdo.it/PrincessGod/g2PE).

BW.

**Comment by cx20** [comment]
Thanks!

**Comment by cx20** [comment]
@PrincessGod Is it possible to specify crossOrigin for glTF files?
http://jsdo.it/cx20/sEKU

![image](https://user-images.githubusercontent.com/1833979/39610258-12af517e-4f8a-11e8-8b1e-e6c68ba5a069.png)

```
czpg.js:6481 
Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': The image element contains cross-origin data, and may not be loaded.
    at setTextureFromElement (https://cdn.rawgit.com/cx20/gltf-test/91ebb79a/libs/czpg/20180503/czpg.js:6481:12)
    at loadImage (https://cdn.rawgit.com/cx20/gltf-test/91ebb79a/libs/czpg/20180503/czpg.js:6505:13)
    at Image.onLoad (https://cdn.rawgit.com/cx20/gltf-test/91ebb79a/libs/czpg/20180503/czpg.js:6200:9)
```

**Comment by PrincessGod** [comment]
@cx20  HAHA...
 You just have to add this line
```js
71    textures.forEach(texture => texture.crossOrigin = 'anonymous');
```
And I will add anonymous crossOrigin automatically : )

Sample [http://jsdo.it/PrincessGod/mpNn](http://jsdo.it/PrincessGod/mpNn)

**Comment by PrincessGod** [comment]
@cx20  Hi

I have automatically add `crossOrigin='anonymous'` for image if necessary.

So you do not have to add it manually if crossOrigin is anonymous.
