### ISSUE TITLE
Part of the bear model is not displayed

### ISSUE THREAD

**Issue by cx20** [PrincessGod/CraZyPG#5]
I tried to display the model of [the bear in sketchfab](https://sketchfab.com/models/f2f13a8630004b1c82730d8b9ffa0e1f) with CZPG.js.

However, it seems that part of the bear model is not displayed.
Balloons are displayed, but bears are not displayed.

http://jsdo.it/cx20/CZ2w

![image](https://user-images.githubusercontent.com/1833979/39613852-e5b2e9d0-4fa5-11e8-9b21-984801e9c32a.png)

**Comment by PrincessGod** [comment]
@cx20  Emmmm, another bug, fixed! thanks!

**Comment by cx20** [comment]
I confirmed that the bear was displayed correctly.
http://jsdo.it/cx20/CZ2w
![image](https://user-images.githubusercontent.com/1833979/39615124-5a2a554c-4faf-11e8-8437-d14c19f7d061.png)
