### ISSUE TITLE
When you load a specific model, setUniformObj becomes undefined

### ISSUE THREAD

**Issue by cx20** [PrincessGod/CraZyPG#7]
I tried to display the following model in CZPG.js.
https://github.com/mrdoob/rome-gltf/blob/master/files/models/life_soup/quadruped_fox.gltf

However, it seems that the following error is output to the console and can not be displayed.
http://jsdo.it/cx20/eOoY
```
czpg.js:12460 
Uncaught TypeError: Cannot read property 'setUniformObj' of undefined
    at setTarget (czpg.js:12460)
    at Animator.update (czpg.js:12410)
    at Render.callback (eOoY:162)
    at Render.run (czpg.js:5142)
```

**Comment by cx20** [comment]
BTW, when you use github's resource from outside, you need to go through [rawgit](https://rawgit.com/) service.
Therefore, the actual URL to read is below.
https://cdn.rawgit.com/mrdoob/rome-gltf/784089b4/files/models/life_soup/quadruped_fox.gltf

**Comment by PrincessGod** [comment]
@cx20  Hi

I just test this model locally, and this model have 10 Morph Targets.

Therefor we have 10 * 2 (POSITION + NORMAL) + 2 (POSITION + NORMAL)  = 22 attributes

but different machine have different gl.MAX_VERTEX_ATTRIBS limit, and my computer is 16.
So it will create program filed and broken....

I do not have a good ideal to handle these...
Maybe just drop morph when it greater than limit range?

**Comment by cx20** [comment]
@PrincessGod Sorry, I forgot that there is a problem with the maximum value of Vertex Attribute in this model.
https://github.com/AnalyticalGraphicsInc/cesium/issues/6432

There are several libraries that can be displayed, but it is unclear how they are realized.

**Comment by PrincessGod** [comment]
@cx20  Optimized, dorp morph attributes which greater than max vertex attributes.

**Comment by PrincessGod** [comment]
@cx20  Hi

I optimized morph target problem, use the targets decided by weights, which means use the bigger weight targets each frame.

Also, about the fox model, you can set `Shader` not CULL_FACE by

```js
gltfShader.cullFace = false;
```

**Comment by cx20** [comment]
@PrincessGod Thanks! Now I confirmed that the model works.
http://jsdo.it/cx20/eOoY
![image](https://user-images.githubusercontent.com/1833979/39673427-e092fd28-5176-11e8-9a72-ccc2e76c6d69.png)
