### ISSUE TITLE
The orientation in which a specific model is displayed is different from other libraries

### ISSUE THREAD

**Issue by cx20** [PrincessGod/CraZyPG#8]
I tried to display the following model in CZPG.js.

https://github.com/cx20/jsdo-static-contents/tree/master/models/gltf/2.0/EmaSimpleSkin_blender/glTF

In CZPG.js, models are displayed vertically, but in other libraries it seems to be displayed beside.

[CZPG.js + EmaSimpleSkin_blender.gltf result:](http://jsdo.it/cx20/kych)
![image](https://user-images.githubusercontent.com/1833979/39617274-069b4656-4fba-11e8-8bc0-a5a71ef8b3b2.png)

[Three.js + EmaSimpleSkin_blender.gltf result:](http://jsdo.it/cx20/6vRt)
![image](https://user-images.githubusercontent.com/1833979/39617292-169923ca-4fba-11e8-96a8-dc0a945118c5.png)

[Babylon.js + EmaSimpleSkin_blender.gltf result:](http://jsdo.it/cx20/EGIL)
![image](https://user-images.githubusercontent.com/1833979/39617355-5cafbcca-4fba-11e8-8d69-56733051ea37.png)

**Comment by PrincessGod** [comment]
@cx20  fixed, thanks!

**Comment by cx20** [comment]
@PrincessGod  Thanks! I confirmed that this problem has been fixed.
http://jsdo.it/cx20/kych
![image](https://user-images.githubusercontent.com/1833979/39625222-7dafaec2-4fd7-11e8-9ad3-d329b2a21bd8.png)
